payment/urls.py
from django.urls import path, include
from .views import CustomerViewSet, UserViewSet, TransferViewSet
from rest_framework.routers import SimpleRouter

app_name = 'payment'
router = SimpleRouter()
router.register('users', UserViewSet, basename='users')
router.register('customers', CustomerViewSet, basename='customers')


urlpatterns = [
    path('', include(router.urls)),
    path('transfer/', TransferViewSet.as_view({'post': 'create'}), name='transfer'),
]

wallet/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view

from payment.views import base_view

API_TITLE = 'Wallet API'
API_DESCRIPTION = 'A Web API for creating and editing customers wallet.'
schema_view = get_swagger_view(title=API_TITLE)


urlpatterns = [
    path('', base_view, name='base'),
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
    path('api/api_auth/', include('rest_framework.urls')),
    path('api/rest_auth/', include('rest_auth.urls')),
    path('api/rest_auth/registration', include('rest_auth.registration.urls')),
    path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    path('swagger-docs/', schema_view),
]

payment/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Customer(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=20, blank=False, unique=True)
    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=150, blank=False)
    email = models.EmailField(blank=False, unique=True)
    date_of_birth = models.DateField(max_length=150, blank=False)
    verified = models.BooleanField(default=False)
    phone_regex = RegexValidator(regex=r'^996\d{9}$',
                                 message="Phone number must be entered in the format: '996*********'. Up to 12 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True, unique=True)

    def __str__(self):
        return self.username


class Balance(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0, blank=True)

    def __str__(self):
        return f"Customer {self.customer} has {self.amount}$"

payment/forms.py
from rest_framework import serializers


class TransferForm(serializers.Serializer):
    phone_number = serializers.CharField(max_length=20)
    amount = serializers.DecimalField(max_digits=10, decimal_places=2)

payment/views.py
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework import viewsets, status
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from payment.forms import TransferForm
from payment.models import Customer, Balance
from payment.permissions import IsOwnerOrReadOnly
from payment.serialaizers import CustomerSerializer, UserSerializer
from django.db import transaction

from payment.tasks import send_transaction_notification_email


def base_view(request):
    return render(request, 'base.html')


class CustomerViewSet(viewsets.ModelViewSet):
    permission_classes = (IsOwnerOrReadOnly,)
    serializer_class = CustomerSerializer

    def get_queryset(self):
        return Customer.objects.filter(author=self.request.user)


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAdminUser,)
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


class TransferViewSet(viewsets.ViewSet):
    permission_classes = (IsOwnerOrReadOnly,)

    def create(self, request):
        serializer = TransferForm(data=request.data)
        serializer.is_valid(raise_exception=True)
        recipient_phone_number = serializer.validated_data.get('phone_number')
        amount = serializer.validated_data.get('amount')
        current_customer = request.user.customer

        try:
            recipient_customer = Customer.objects.get(phone_number=recipient_phone_number)
        except Customer.DoesNotExist:
            return Response({'error': 'Recipient not found.'}, status=status.HTTP_404_NOT_FOUND)
        if recipient_customer == current_customer:
            return Response({'error': 'Cannot transfer money to yourself.'}, status=status.HTTP_400_BAD_REQUEST)
        if current_customer.balance.amount < amount:
            return Response({'error': 'Insufficient balance.'}, status=status.HTTP_400_BAD_REQUEST)
        with transaction.atomic():
            current_customer.balance.amount -= amount
            current_customer.balance.save()
            recipient_customer.balance.amount += amount
            recipient_customer.balance.save()
        send_transaction_notification_email(recipient_customer.email, amount)
        return Response({'success': 'Money transferred successfully.'}, status=status.HTTP_200_OK)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>
<form method="POST" action="{% url 'payment:transfer' %}">
    {% csrf_token %}
    <label for="phone_number">Recipient Phone Number:</label>
    <input type="text" name="phone_number" id="phone_number" required>
    <br>
    <label for="amount">Amount:</label>
    <input type="number" name="amount" id="amount" min="1" required>
    <br>
    <button type="submit">Transfer</button>
</form>

<form method="post" action="{% url 'rest_login' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" required><br><br>
    <label for="password">Password:</label>
    <input type="password" name="password" required><br><br>
    <button type="submit">Login</button>
</form>


</body>
</html>

templates/transfer.html
{% extends 'base.html' %}

{% block content %}
  <h2>Transfer Funds</h2>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="sender">Sender:</label>
      <input type="text" id="sender" name="sender" value="{{ sender.phone_number }}" readonly>
    </div>
    <div>
      <label for="receiver">Receiver:</label>
      <input type="tel" id="receiver" name="receiver" required>
    </div>
    <div>
      <label for="amount">Amount:</label>
      <input type="number" id="amount" name="amount" min="1" required>
    </div>
    <button type="submit">Transfer</button>
  </form>
{% endblock %}